services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - ./backend/.env  # Ensure the .env file exists or use environment variables directly
